# HISTORICAL SOCKEYE ANALYSIS - CLEMENS & GILBERT
# Created by C Freshwater JAN 21, 2018
# Last revised: ONGOING
# Uses cleaned data generated by NASS_Jan2018_CFedits.R
# to model relationship between regional environmental drivers
# and historical changes in sockeye body size
# -------------------------------------------------

library(here); 
library(mgcv); library(dplyr); library(ggplot2); library(reshape2);
library(MuMIn); library(corrplot); library(car); library(mgcv.helper)


source(here::here("scripts/histSockeyeFunc.R"))

sstPca <- read.table(here("data/sstPCA.txt")) #principal components of SST variation in NE Pacific (170E to 240E, 40N-65N)
sstRaw <- read.table(here("data/sstRaw.txt")) # pacific ocean SST
pdo <- read.csv(here("data/pdo.csv"), stringsAsFactors=F) 
meanAlpi <- read.csv(here("data/alpi.csv"), stringsAsFactors=F) #stops at 2015
sockDat <- read.csv(here("data/nassFullSox.csv"), stringsAsFactors=F)
catchDat <- read.csv(here("data/akCatch.csv"), stringsAsFactors=F)


## ---------------------- Clean ------------------------------
### sst PCA
colnames(sstPca) <- c("id", "retYr", "month", "pc1", "pc2", "pc3", "pc4", "pc5")
months <- c("3","4","5","6")
sstPca <- sstPca[sstPca$month %in% months, c("retYr","month","pc2")] 
meanPca <- sstPca %>%
	group_by(retYr) %>%
	summarise(pc2=mean(pc2))

### sst raw
colnames(sstRaw) <- c("long", "lat", "retYr", "month", "temp")
months <- c("3","4","5","6")
sstRaw <- sstRaw[sstRaw$month %in% months, c("retYr","month","temp")] 
meanSst <- sstRaw %>%
	group_by(retYr) %>%
	summarise(temp=mean(temp))

### pdo
meanPdo <- data.frame(retYr=pdo$YEAR,
					  pdo=apply(pdo[,c("MAR","APR","MAY","JUN")], 1, mean)
					  )

### alpi
names(meanAlpi)[1:2] <- c("retYr", "alpi")

### catch
sockCatch <- catchDat[catchDat$species=="Sockeye", -c(1,2,4)]
names(sockCatch)[c(1,2)] <- c("retYr", "sockCatch")
pinkCatch <- catchDat[catchDat$species=="Pink", -c(1,2,4)]
names(pinkCatch)[c(1,2)] <- c("retYr", "pinkCatch")
totalCatch <- data.frame(retYr = sockCatch$retYr, 
                         totalCatch = (sockCatch$sockCatch + 
                                         pinkCatch$pinkCatch))

### merge sox data w/ environmental
fullDat <- Reduce(function(x, y) merge(x, y, by=c("retYr")), 
                  list(sockDat, meanPdo, meanSst, meanPca, meanAlpi, sockCatch, 
                       pinkCatch, totalCatch))
fullDat <- standardizeVar(fullDat)

nassDat <- subset(fullDat, fullDat$watershed %in% "nass")
nassDatMod <- subset(nassDat, nassDat$dataSet %in% "mod")
nassDat <- subset(nassDat, nassDat$dataSet %in% "hist")
riversDat <- subset(fullDat,fullDat$watershed %in% "rivers")

nassDat$age <- factor(nassDat$age)
nassDat$yrFac <- factor(nassDat$retYr)
nassDatMod$age <- factor(nassDatMod$age)
nassDatMod$yrFac <- factor(nassDatMod$retYr)
riversDat$age <- factor(riversDat$age)
riversDat$yrFac <- factor(riversDat$retYr)

datList <- list(nassDat, nassDatMod, riversDat)


datListN <- lapply(datList, function(x) standardizeVar(x))
names(datListN) <- c("nassDat", "nassDatMod", "riversDat")


# correlations among predictor variables
makeCorPlot <- function(df){
	mat <- cor(df[,c("pc2Std", "tempStd", "pdoStd", "alpiStd", "sockStd", "pinkStd", "totalStd")])
	figTitle <- paste(unique(df$watershed), unique(df$dataSet), sep=" ")
	corrplot.mixed(mat, lower="ellipse", upper="number")
	mtext(side=3, line=1.5, figTitle, cex=1.2)
}

pdf(here("github/histSockeye/outputs/figs/corrPlot.pdf"), height=10, width=10)
par(mfrow=c(2,2), mar=c(0,0,2.75,0)+0.1, oma=c(0,0,0,0))
sapply(datListN, function(x) makeCorPlot(x))
dev.off()


## ---------------------- Plot raw size trends ------------------------------
meanDat <- fullDat %>%
	group_by(retYr, age, watershed, dataSet) %>%
	summarize(meanFL = mean(fl), pdo = mean(pdo), alpi = mean(alpi), 
		rawSst = mean(temp), pcaSst = mean(pc2), pink = mean(pinkCatch), 
		sox = mean(sockCatch))

meanDat$dummy <- with(meanDat, interaction(watershed, dataSet))

## Changes in length through time
index <- unique(meanDat$dummy)
pdf(here("github/histSockeye/outputs/figs/linearTrends.pdf"), height=6, width=6)
for(i in seq_along(index)) {
	d <- meanDat[meanDat$dummy == index[i], ]
	p <- ggplot(d, aes(x = as.numeric(retYr), y = meanFL, col = as.factor(age))) + 
    	geom_point() + 
    	geom_smooth(method = "lm") +
    	ggtitle(index[i])
    print(p)
}
dev.off()

# meanDat$dummy <- with(meanDat, interaction(watershed, dataSet))
pdf(here("github/histSockeye/outputs/figs/phenologyTrends.pdf"), height=6, width=6)
sockDat$dummy <- with(sockDat, interaction(watershed, dataSet))
ggplot(sockDat, aes(x = jDay, y = fl, col = as.factor(age))) + 
    	# geom_point() + 
    	geom_smooth(method = "lm") +
    	facet_wrap(~dummy)
dev.off()

# ------------------------------------------------------
## Full model comparison with different environmental covariates; removed AR1 terms because they don't seem to be doing anything
# for(i in seq_along(datListN)){
# 	dataset <- datListN[[i]]
# 	dataset$dum <- 1
	
# 	# models
# 	null <- gam(fl ~ age + s(yrFac, bs="re", by=dum), method="ML", data=dataset)
# 	pdo <- gam(fl ~ s(pdoStd, by=age, k=3) + age + s(yrFac, bs="re", by=dum), method="ML", data=dataset)
# 	temp <- gam(fl ~ s(tempStd, by=age, k=3) + age + s(yrFac, bs="re", by=dum), method="ML", data=dataset)
# 	pc2 <- gam(fl ~ s(pc2Std, by=age, k=3) + age + s(yrFac, bs="re", by=dum), method="ML", data=dataset)
# 	alpi <- gam(fl ~ s(alpiStd, by=age, k=3) + age + s(yrFac, bs="re", by=dum), method="ML", data=dataset)
# 	pink <- gam(fl ~ s(pinkStd, by=age, k=3) + age + s(yrFac, bs="re", by=dum), method="ML", data=dataset)
# 	sock <- gam(fl ~ s(sockStd, by=age, k=3) + age + s(yrFac, bs="re", by=dum), method="ML", data=dataset)
# 	total <- gam(fl ~ s(totalStd, by=age, k=3) + age + s(yrFac, bs="re", by=dum), method="ML", data=dataset)
# 	pdoPink <- gam(fl ~ s(pdoStd, by=age, k=3) + s(pinkStd, by=age, k=3) + age + s(yrFac, bs="re", by=dum), method="ML", data=dataset)
# 	tempPink <- gam(fl ~ s(tempStd, by=age, k=3) + s(pinkStd, by=age, k=3) + age + s(yrFac, bs="re", by=dum), method="ML", data=dataset)
# 	pc2Pink <- gam(fl ~ s(pc2Std, by=age, k=3) + s(pinkStd, by=age, k=3) + age + s(yrFac, bs="re", by=dum), method="ML", data=dataset)
# 	alpiPink <- gam(fl ~ s(alpiStd, by=age, k=3) + s(pinkStd, by=age, k=3) + age + s(yrFac, bs="re", by=dum), method="ML", data=dataset)
# 	pdoSock <- gam(fl ~ s(pdoStd, by=age, k=3) + s(sockStd, by=age, k=3) + age + s(yrFac, bs="re", by=dum), method="ML", data=dataset)
# 	tempSock <- gam(fl ~ s(tempStd, by=age, k=3) + s(sockStd, by=age, k=3) + age + s(yrFac, bs="re", by=dum), method="ML", data=dataset)
# 	pc2Sock <- gam(fl ~ s(pc2Std, by=age, k=3) + s(sockStd, by=age, k=3) + age + s(yrFac, bs="re", by=dum), method="ML", data=dataset)
# 	alpiSock <- gam(fl ~ s(alpiStd, by=age, k=3) + s(sockStd, by=age, k=3) + age + s(yrFac, bs="re", by=dum), method="ML", data=dataset)
# 	pdoTotal <- gam(fl ~ s(pdoStd, by=age, k=3) + s(totalStd, by=age, k=3) + age + s(yrFac, bs="re", by=dum), method="ML", data=dataset)
# 	tempTotal <- gam(fl ~ s(tempStd, by=age, k=3) + s(totalStd, by=age, k=3) + age + s(yrFac, bs="re", by=dum), method="ML", data=dataset)
# 	pc2Total <- gam(fl ~ s(pc2Std, by=age, k=3) + s(totalStd, by=age, k=3) + age + s(yrFac, bs="re", by=dum), method="ML", data=dataset)
# 	alpiTotal <- gam(fl ~ s(alpiStd, by=age, k=3) + s(totalStd, by=age, k=3) + age + s(yrFac, bs="re", by=dum), method="ML", data=dataset)

# 	modOutputs <- list(null, pdo, temp, pc2, alpi, pink, sock, total, pdoPink, tempPink, pc2Pink, alpiPink, 
# 		pdoSock, tempSock, pc2Sock, alpiSock, pdoTotal, tempTotal, pc2Total, alpiTotal)
# 	names(modOutputs)[1:length(modOutputs)] <- c("null", "pdo", "temp", "pc2", "alpi", "pink", "sock", "total", "pdoPink", "tempPink", "pc2Pink", "alpiPink", 
# 		"pdoSock", "tempSock", "pc2Sock", "alpiSock", "pdoTotal", "tempTotal", "pc2Total", "alpiTotal")
# 	assign(paste("fits", dataset$watershed[1], dataset$dataSet[1], sep="_"), modOutputs)
# 	modRankings <- AICc(null, pdo, temp, pc2, alpi, pink, sock, total, pdoPink, tempPink, pc2Pink, alpiPink, 
# 		pdoSock, tempSock, pc2Sock, alpiSock, pdoTotal, tempTotal, pc2Total, alpiTotal)
# 	modRankings <- modRankings[order(modRankings$AICc),]
# 	print(modRankings)
# 	assign(paste("ranking", dataset$watershed[1], dataset$dataSet[1], sep="_"), modRankings)
# }

# save data files
# saveRDS(fits_nass_mod, here("github/histSockeye/outputs/data/nassModernModFits.rds"))
# saveRDS(fits_nass_hist, here("github/histSockeye/outputs/data/nassHistoricModFits.rds"))
# saveRDS(fits_rivers_hist, here("github/histSockeye/outputs/data/riversHistoricModFits.rds"))

# read in data files
# fits_nass_mod <- readRDS(here("github/histSockeye/outputs/data/nassModernModFits.rds"))
# fits_nass_hist <- readRDS(here("github/histSockeye/outputs/data/nassHistoricModFits.rds"))
# fits_rivers_hist <- readRDS(here("github/histSockeye/outputs/data/riversHistoricModFits.rds"))

# extract top models 
nhTempPink <- gam(fl ~ s(tempStd, by=age, k=3) + s(pinkStd, by=age, k=3) + age + s(yrFac, bs="re"), 
				  method="REML", data=datListN$nassDat)
nhTemp <- gam(fl ~ s(tempStd, by=age, k=3) + age + s(yrFac, bs="re"), 
				  method="REML", data=datListN$nassDat)
nhPink <- gam(fl ~ s(pinkStd, by=age, k=3) + age + s(yrFac, bs="re"), 
				  method="REML", data=datListN$nassDat)
rhPdoPink <- gam(fl ~ s(pdoStd, by=age, k=3) + s(pinkStd, by=age, k=3) + age + s(yrFac, bs="re"),
				 method="REML", data=datListN$riversDat)
nmPc2Pink <- gam(fl ~ s(pc2Std, by=age, k=3) + s(pinkStd, by=age, k=3) + age + s(yrFac, bs="re"),
			 	 method="REML", data=datListN$nassDatMod)
topModList <- list(nmPc2Pink, nhTempPink, rhPdoPink)
names(topModList) <- c("N Mod", "N His", "R His")

# check models
sapply(topModList, function(x) gam.check(x))# some issues with modern model's qq plot, perhaps increase k?
sapply(topModList, function(x) acf(residuals(x), main="")) #substantially more AC in modern model

summary(nmPc2Pink)
summary(nmPc2Sock)
summary(nhTempPink)
summary(rhPdoPink)

nhTempSock <- gam(fl ~ s(tempStd, by=age, k=3) + s(sockStd, by=age, k=3) + age + s(yrFac, bs="re"), 
				  method="REML", data=datListN$nassDat)
rhPdoSock <- gam(fl ~ s(pdoStd, by=age, k=3) + s(sockStd, by=age, k=3) + age + s(yrFac, bs="re"),
				 method="REML", data=datListN$riversDat)
nmPc2Sock <- gam(fl ~ s(pc2Std, by=age, k=3) + s(sockStd, by=age, k=3) + age + s(yrFac, bs="re"),
			 	 method="REML", data=datListN$nassDatMod)


## Fit equivalent models with gamm so vif can be evaluated
# rhPdoPinkAR <- gamm(fl ~ s(pdoStd, by=age, k=3) + s(pinkStd, by=age, k=3) + age, 
# 	random=list(yrFac = ~1),  correlation = corAR1(form = ~ yrFac), method="REML", data=datListN$riversDat)
# rhPdoPink <- gamm(fl ~ s(pdoStd, by=age, k=3) + s(pinkStd, by=age, k=3) + age, 
# 	random=list(yrFac = ~1), method="REML", data=datListN$riversDat)
# nhTempPink <- gamm(fl ~ s(tempStd, by=age, k=3) + s(pinkStd, by=age, k=3) + age, 
# 	random=list(yrFac = ~1), method="REML", data=datListN$nassDat)
# nmPc2Pink <- gamm(fl ~ s(pc2Std, by=age, k=3) + s(pinkStd, by=age, k=3) + age, 
# 	random=list(yrFac = ~1), method="REML", data=datListN$nassDatMod)
# # rhPdoSockX <- gamm(fl ~ s(pdoStd, by=age, k=3) + s(sockStd, by=age, k=3) + age, random=list(yrFac = ~1), method="REML", data=datListN$riversDat)
# # nhTempSockX <- gamm(fl ~ s(tempStd, by=age, k=3) + s(sockStd, by=age, k=3) + age, random=list(yrFac = ~1), method="REML", data=datListN$nassDat)
# # nmPc2SockX <- gamm(fl ~ s(pc2Std, by=age, k=3) + s(sockStd, by=age, k=3) + age, random=list(yrFac = ~1), method="REML", data=datListN$nassDatMod)

# gam.check(rhPdoPink$gam)
# gam.check(nhTempPink$gam)
# gam.check(nmPc2Pink$gam)

# acf(resid(nhTempPink$gam))
# acf(resid(nhTempPink$lme))

# Plot ts of length and predictors ---------------------------------------
plotTS <- function(meanDat, dat){
	temp <- data.frame(retYr = seq(from=min(dat$retYr), to=max(dat$retYr), by=1),
		yrFac = as.factor(seq(from=min(dat$retYr), to=max(dat$retYr), by=1)))
	temp$meanFL <- meanDat$meanFL[match(temp$yrFac, meanDat$yrFac)]
	temp$meanP1 <- meanDat$meanP1[match(temp$yrFac, meanDat$yrFac)]
	temp$meanP2 <- meanDat$meanP2[match(temp$yrFac, meanDat$yrFac)]
	figTitle <- paste(unique(dat$watershed), unique(dat$dataSet), sep=" ")

	x <- plot(temp$meanFL ~ temp$retYr, type="l", axes=FALSE, lwd=1.5, xlab="", ylab="")
	axis(1, tick=T, at=pretty(c(seq(from=min(temp$retYr), to=max(temp$retYr), by=5)), n=4))
	axis(2, tick=T, at=pretty(c(seq(from=min(temp$meanFL, na.rm=TRUE), to=max(temp$meanFL, na.rm=TRUE), by=5)), n=4))
	mtext(side=2, line=2.5, 'Mean Fork Length', cex=1.2)
	mtext(side=3, line=1.25, figTitle, cex=1.2)
	par(new=TRUE)
	x <- plot(temp$meanP1 ~ temp$retYr, type="l", col="#1b9e77", axes=F, xlab="", ylab="", lty=2, lwd=1.25,
		ylim=c(min(temp$meanP1, na.rm=T), max(temp$meanP1, na.rm=T)))
	lines(temp$meanP2~ temp$retYr, type="l", col="#7570b3", xlab="", ylab="", lty=2, lwd=1.25,
		ylim=c(min(temp$meanP2, na.rm=T), max(temp$meanP2, na.rm=T)))
	return(x)
}

meanNass <- datListN[[1]] %>% 
			group_by(yrFac) %>% 
			summarize(meanFL = mean(fl), meanP1 = mean(tempStd), meanP2 = mean(pinkStd))
meanNassMod <- datListN[[2]] %>% 
			group_by(yrFac) %>% 
			summarize(meanFL = mean(fl), meanP1 = mean(pc2Std), meanP2 = mean(pinkStd))
meanRiv <- datListN[[3]] %>% 
			group_by(yrFac) %>% 
			summarize(meanFL = mean(fl), meanP1 = mean(pdoStd), meanP2 = mean(pinkStd))

pdf(here("github/histSockeye/outputs/figs/timeseries.pdf"), height=10, width=8)
par(mfrow=c(3,1), mar=c(4,4,3,0)+0.1, oma=c(0,0,0,0))
plotTS(meanNass, datListN[[1]])
legend("topleft", c("Fork Length", "Environmental", "Catch"), 
	col=c("black", "#1b9e77", "#7570b3"), lty=c(1,2,2), bty="n", cex=1.5)
plotTS(meanNassMod, datListN[[2]])
plotTS(meanRiv, datListN[[3]])
dev.off()



# Clean figures of predictions -------------------------------------------

## Nass modern (also look at sockeye model)
## Mean response across PC2, i.e. pink at mean
newNModTempDat <- data.frame(yrFac=rep(unique(nassDatMod$yrFac), length.out=400), 
					sockStd=rep(0, length=400),
					pc2Std=rep(seq(from=-1.75, to=2.5, length=100), times=4),
					age=rep(c("1.2", "1.3", "2.2", "2.3"), each=100)
					)
predNModTempDat <- predict(nmPc2Sock, newNModTempDat, se.fit = TRUE, exclude = "s(yrFac)")
predNModTempDat <- with(predNModTempDat, data.frame(newNModTempDat,
								response = fit,
								lwr = (fit - 2*se.fit),
								upr = (fit + 2*se.fit)))

## Mean response across pinks, i.e. PC2 at mean
newNModSockDat <- data.frame(yrFac=rep(unique(nassDatMod$yrFac), length.out=400), 
					pc2Std=rep(0, length=400),
					sockStd=rep(seq(from=-1.5, to=3, length=100), times=4),
					age=rep(c("1.2", "1.3", "2.2", "2.3"), each=100)
					)
predNModSockDat <- predict(nmPc2Sock, newNModSockDat, se.fit = TRUE, exclude = "s(yrFac)")
predNModSockDat <- with(predNModSockDat, data.frame(newNModSockDat,
								response = fit,
								lwr = (fit - 2*se.fit),
								upr = (fit + 2*se.fit)))

## Mean age intercepts
newNModAgeDat <- data.frame(yrFac=rep(unique(nassDatMod$yrFac), length.out=400), 
					pc2Std=rep(0, length=400),
					sockStd=rep(0, length=400),
					age=rep(c("1.2", "1.3", "2.2", "2.3"), each=100)
					)
predNModAgeDat <- predict(nmPc2Sock, newNModAgeDat, se.fit = TRUE, exclude = "s(yrFac)")
predNModAgeDat <- with(predNModAgeDat, data.frame(newNModAgeDat,
								response = fit,
								lwr = (fit - 2*se.fit),
								upr = (fit + 2*se.fit)))

nassModTempFig <- ggplot(predNModTempDat, aes(x = pc2Std, y = response, colour = age)) +
	geom_ribbon(aes(ymin = lwr, ymax = upr, fill = age), alpha = 0.1) +
	geom_line(aes(colour = age)) +
	ylab("Fork Length") +
	xlab("Standardized Nearshore PC2") +
	ggtitle("Mod Nass PC2 Predictions")

nassModSockFig <- ggplot(predNModSockDat, aes(x = sockStd, y = response, colour = age)) +
	geom_ribbon(aes(ymin = lwr, ymax = upr, fill = age), alpha = 0.1) +
	geom_line(aes(colour = age)) +
	ylab("Fork Length") +
	xlab("Standardized Sockeye Abundance") +
	ggtitle("Mod Nass Sockeye Salmon Predictions")

nassModAgeFig <- ggplot(predNModAgeDat, aes(x = age, y = response, ymin = lwr, ymax = upr, colour = age)) +
	geom_point() +
	geom_errorbar(position = position_dodge(width = 0.2), width = 0.1) +
	ylab("Fork Length") +
	xlab("Age") +
	ggtitle("Mod Nass")

## Nass historic (also look at sockeye model)
## Mean response across temp, i.e. pink at mean
newNTempDat <- data.frame(yrFac=rep(unique(nassDat$yrFac), length.out=400), 
					sockStd=rep(0, length=400),
					tempStd=rep(seq(from=-2.75, to=2.25, length=100), times=4),
					age=rep(c("1.2", "1.3", "2.2", "2.3"), each=100)
					)
predNTempDat <- predict(nhTempSock, newNTempDat, se.fit = TRUE, exclude = "s(yrFac)")
predNTempDat <- with(predNTempDat, data.frame(newNTempDat,
								response = fit,
								lwr = (fit - 2*se.fit),
								upr = (fit + 2*se.fit)))

## Mean response across pinks, i.e. SST at mean
newNSockDat <- data.frame(yrFac=rep(unique(nassDat$yrFac), length.out=400), 
					tempStd=rep(0, length=400),
					sockStd=rep(seq(from=-1.5, to=3, length=100), times=4),
					age=rep(c("1.2", "1.3", "2.2", "2.3"), each=100)
					)
predNSockDat <- predict(nhTempSock, newNSockDat, se.fit = TRUE, exclude = "s(yrFac)")
predNSockDat <- with(predNSockDat, data.frame(newNSockDat,
								response = fit,
								lwr = (fit - 2*se.fit),
								upr = (fit + 2*se.fit)))

## Mean response across ages
newAgeDat <- data.frame(yrFac=rep(unique(nassDat$yrFac), length.out=400), 
					tempStd=rep(0, length=400),
					sockStd=rep(0, length=400),
					age=rep(c("1.2", "1.3", "2.2", "2.3"), each=100)
					)
predAgeDat <- predict(nhTempSock, newAgeDat, se.fit = TRUE, exclude = "s(yrFac)")
predAgeDat <- with(predAgeDat, data.frame(newAgeDat,
								response = fit,
								lwr = (fit - 2*se.fit),
								upr = (fit + 2*se.fit)))

nassHistTempFig <- ggplot(predNTempDat, aes(x = tempStd, y = response, colour = age)) +
geom_ribbon(aes(ymin = lwr, ymax = upr, fill = age), alpha = 0.1) +
geom_line(aes(colour = age)) +
ylab("Fork Length") +
xlab("Standardized Nearshore SST") +
ggtitle("Nass SST Predictions")

nassHistSockFig <- ggplot(predNSockDat, aes(x = sockStd, y = response, colour = age)) +
geom_ribbon(aes(ymin = lwr, ymax = upr, fill = age), alpha = 0.1) +
geom_line(aes(colour = age)) +
ylab("Fork Length") +
xlab("Standardized Sockeye Abundance") +
ggtitle("Nass Sockeye Salmon Predictions")

nassAgeFig <- ggplot(predAgeDat, aes(x = age, y = response, ymin = lwr, ymax = upr, colour = age)) +
	geom_point() +
	geom_errorbar(position = position_dodge(width = 0.2), width = 0.1) +
	ylab("Fork Length") +
	xlab("Age") +
	ggtitle("Hist Nass")


## Rivers (historic)
## Mean response across SST, i.e. pink at mean
newRPdoDat <- data.frame(yrFac=rep(unique(riversDat$yrFac), length.out=400), 
					sockStd=rep(0, length=400),
					pdoStd=rep(seq(from=-2.5, to=2, length=100), times=4),
					age=rep(c("1.2", "1.3"), each=200)
					)
predRPdoDat <- predict(rhPdoSock, newRPdoDat, se.fit = TRUE, exclude = "s(yrFac)")
predRPdoDat <- with(predRPdoDat, data.frame(newRPdoDat,
								response = fit,
								lwr = (fit - 2*se.fit),
								upr = (fit + 2*se.fit)))

## Mean response across pinks, i.e. SST at mean
newRSockDat <- data.frame(yrFac=rep(unique(riversDat$yrFac), length.out=400), 
					pdoStd=rep(0, length=400),
					sockStd=rep(seq(from=-2.5, to=2, length=100), times=4),
					age=rep(c("1.2", "1.3"), each=200)
					)
predRSockDat <- predict(rhPdoSock, newRSockDat, se.fit = TRUE, exclude = "s(yrFac)")
predRSockDat <- with(predRSockDat, data.frame(newRSockDat,
								response = fit,
								lwr = (fit - 2*se.fit),
								upr = (fit + 2*se.fit)))

## Mean differences in age 
newAgeDat <- data.frame(yrFac=rep(unique(riversDat$yrFac), length.out=400), 
					pdoStd=rep(0, length=400),
					sockStd=rep(0, length=400),
					age=rep(c("1.2", "1.3"), each=200)
					)
predAgeDat <- predict(rhPdoSock, newAgeDat, se.fit = TRUE, exclude = "s(yrFac)")
predAgeDat <- with(predAgeDat, data.frame(newAgeDat,
								response = fit,
								lwr = (fit - 2*se.fit),
								upr = (fit + 2*se.fit)))

rivPdoFig <- ggplot(predRPdoDat, aes(x = pdoStd, y = response, colour = age)) +
geom_ribbon(aes(ymin = lwr, ymax = upr, fill = age), alpha = 0.1) +
geom_line(aes(colour = age)) +
ylab("Fork Length") +
xlab("Standardized PDO") +
ggtitle("Rivers PDO Predictions")

rivSockFig <- ggplot(predRSockDat, aes(x = sockStd, y = response, colour = age)) +
geom_ribbon(aes(ymin = lwr, ymax = upr, fill = age), alpha = 0.1) +
geom_line(aes(colour = age)) +
ylab("Fork Length") +
xlab("Standardized Sockeye Abundance") +
ggtitle("Rivers Sockeye Salmon Predictions")

rivAgeFig <- ggplot(predAgeDat, aes(x = age, y = response, ymin = lwr, ymax = upr, colour = age)) +
	geom_point() +
	geom_errorbar(position = position_dodge(width = 0.2), width = 0.1) +
	ylab("Fork Length") +
	xlab("Age") +
	ggtitle("Hist Rivers")

# Save figures
pdf(here("github/histSockeye/outputs/figs/predictionsSox.pdf"), height=4, width=4)
theme_set(theme_bw())
par(mfrow=c(1,3), mar=c(0,0,2.75,0)+0.1, oma=c(0,0,0,0))
rivPdoFig
rivSockFig
rivAgeFig
nassHistTempFig
nassHistSockFig
nassAgeFig
nassModTempFig
nassModSockFig
nassModAgeFig
dev.off()


# Truncated models -------------------------------------------------------
# Truncated models to pass to Skip to compare w/ SST (Mar. 25)
nassDat$dum <- 1	
ltNTrunc1 <- gam(fl ~ s(pinkSE1, by=age, k=3) + age + s(yrFac, bs="re", by=dum), 
	correlation=corAR1(form = ~ 1|yrFac), data=nassDat, method="REML")
ltNTrunc2 <- gam(fl ~ age + s(yrFac, bs="re", by=dum), 
	correlation=corAR1(form = ~ 1|yrFac), data=nassDat, method="REML")
nassDat$residPink <- resid(ltNTrunc1)
nassDat$residNoPink <- resid(ltNTrunc2)
write.csv(nassDat, here("github/histSockeye/outputs/data/nassDatWResids.csv"))

riversDat$dum <- 1	
ltRTrunc1 <- gam(fl ~ s(pinkSE1, by=age, k=3) + age + s(yrFac, bs="re", by=dum), 
	correlation=corAR1(form = ~ 1|yrFac), data=riversDat, method="REML")
ltRTrunc2 <- gam(fl ~ age + s(yrFac, bs="re", by=dum), 
	correlation=corAR1(form = ~ 1|yrFac), data=riversDat, method="REML")
riversDat$residPink <- resid(ltRTrunc1)
riversDat$residNoPink <- resid(ltRTrunc2)
write.csv(riversDat, here("github/histSockeye/outputs/data/riversDatWResids.csv"))



# Out of sample predictions -------------------------------------------
# Predict size in 1970s using top models for each dataset

# Top models 
nhTempPink <- gam(fl ~ s(tempStd, by=age, k=3) + s(pinkStd, by=age, k=3) + age + s(yrFac, bs="re"), 
				  method="REML", data=datList$nassDat)
nhTempPink <- gam(fl ~ s(tempStd, by=age, k=3) + s(pinkStd, by=age, k=3) + age + s(yrFac, bs="re"), 
				  method="REML", data=datListN$nassDat)
rhPdoPink <- gam(fl ~ s(pdoStd, by=age, k=3) + s(pinkStd, by=age, k=3) + age + s(yrFac, bs="re"),
				 method="REML", data=datList$riversDat)
nmPc2Pink <- gam(fl ~ s(pc2Std, by=age, k=3) + s(pinkStd, by=age, k=3) + age + s(yrFac, bs="re"),
			 	 method="REML", data=datList$nassDatMod)

# nhTemp <- gam(fl ~ s(tempStd, by=age, k=3) + age + s(yrFac, bs="re"), 
# 				  method="REML", data=datListN$nassDat)
# nhPink <- gam(fl ~ s(pinkStd, by=age, k=3) + age + s(yrFac, bs="re"), 
# 				  method="REML", data=datListN$nassDat)


# Dataset of predictors
predDat <- Reduce(function(x, y) merge(x, y, by=c("retYr")), list(meanPdo, meanSst, meanPca, meanAlpi, pinkCatch))
stdPredDat <- apply(predDat[,c(2:6)], 2, function(x) (x-mean(x))/sd(x))
colnames(stdPredDat) <- c("pdoStd", "tempStd", "pc2Std", "alpiStd", "pinkStd")
predDat <- cbind(predDat, stdPredDat)
predYrs <- seq(from=1960, to=1980, by=1)
trimPred <- predDat[predDat$retYr %in% predYrs,]
trimPred <- rbind(trimPred, trimPred, trimPred, trimPred) #stack 4 high so that age variables can be added

# Add necessary categorical variables
trimPred$age <- as.factor(rep(c("1.2","1.3","2.2","2.3"), each=nrow(trimPred)/4))
trimPred$yrFac <- as.factor("1935") #dummy variable found in original - model will average across yrs

# Subset w/ appropriate years
trimPredRiv <- trimPred[trimPred$age %in% c("1.2", "1.3"),] #necessary to drop 2 age classes from rivers
trimPredRiv$age <- factor(trimPredRiv$age)
trimPredNM <- trimPred
trimPredNM$yrFac <- as.factor("1996") #dummy variable found in original - model will average across yrs 

# Make predictions with each model
riversPred <- predict(rhPdoPink, newdata=trimPredRiv, se.fit = TRUE, exclude = "s(yrFac)")
riversPred <- with(riversPred, data.frame(trimPredRiv,
								response = fit,
								lwr = (fit - 2*se.fit),
								upr = (fit + 2*se.fit)))

nassPred <- predict(nhTempPink, newdata=trimPred, se.fit=TRUE, exclude="s(yrFac)")
nassPred <- with(nassPred, data.frame(trimPred,
								response = fit,
								lwr = (fit - 2*se.fit),
								upr = (fit + 2*se.fit)))
nassPredTemp <- predict(nhTemp, newdata=trimPred, se.fit=TRUE, exclude="s(yrFac)")
nassPredTemp <- with(nassPredTemp, data.frame(trimPred,
								response = fit,
								lwr = (fit - 2*se.fit),
								upr = (fit + 2*se.fit)))
# nassPredPink <- predict(nhPink, newdata=trimPred, se.fit=TRUE, exclude="s(yrFac)")
# nassPredPink <- with(nassPredPink, data.frame(trimPred,
# 								response = fit,
# 								lwr = (fit - 2*se.fit),
# 								upr = (fit + 2*se.fit)))
# nassModPred <- predict(nmPc2Pink, newdata=trimPredNM, se.fit=TRUE, exclude="s(yrFac)")
# nassModPred <- with(nassModPred, data.frame(trimPredNM,
# 								response = fit,
# 								lwr = (fit - 2*se.fit),
# 								upr = (fit + 2*se.fit)))

predList <- list(riversPred, nassPred, nassModPred)
vars <- c("retYr", "pdo", "temp", "pc2", "alpi", "pinkCatch", "age", "response", "lwr", "upr")
fileNames <- c("riversPredNewStd", "nassPredNewStd", "nassModPredNewStd")

for(i in seq_along(predList)){
	d <- predList[[i]][,vars]
	names(d)[8] <- "predFL"
	fileName <- fileNames[i]
	write.csv(d, paste(here("github/histSockeye/outputs/data/"), fileName, ".csv", sep=""), row.names=FALSE)
}

par(mfrow=c(2,2), oma=c(0,0,0,0)+0.1, mar=(4,4,0,0))
trimList <- c(predList[[2]], predList[[4]], predList[[5]])
sapply(trimList, function(x) hist(trimList$response))




# Repeat analysis w/ full dataset, watersheds as factors -------------------------------------------
# Run with full dataset to see what environmental variable selected
fullDat$dummy <- with(fullDat, interaction(watershed, dataSet, age))
fullDat$dummy <- factor(fullDat$dummy)
fullDat$yrFac <- factor(fullDat$retYr)

# models
null <- gam(fl ~ dummy + s(yrFac, bs="re"), method="ML", data=fullDat)
pdo <- gam(fl ~ s(pdoStd, by=dummy, k=3) + dummy + s(yrFac, bs="re"), method="ML", data=fullDat)
temp <- gam(fl ~ s(tempStd, by=dummy, k=3) + dummy + s(yrFac, bs="re"), method="ML", data=fullDat)
pc2 <- gam(fl ~ s(pc2Std, by=dummy, k=3) + dummy + s(yrFac, bs="re"), method="ML", data=fullDat)
alpi <- gam(fl ~ s(alpiStd, by=dummy, k=3) + dummy + s(yrFac, bs="re"), method="ML", data=fullDat)
pink <- gam(fl ~ s(pinkStd, by=dummy, k=3) + dummy + s(yrFac, bs="re"), method="ML", data=fullDat)
sock <- gam(fl ~ s(sockStd, by=dummy, k=3) + dummy + s(yrFac, bs="re"), method="ML", data=fullDat)
total <- gam(fl ~ s(totalStd, by=dummy, k=3) + dummy + s(yrFac, bs="re"), method="ML", data=fullDat)
pdoPink <- gam(fl ~ s(pdoStd, by=dummy, k=3) + s(pinkStd, by=dummy, k=3) + dummy + s(yrFac, bs="re"), method="ML", data=fullDat)
tempPink <- gam(fl ~ s(tempStd, by=dummy, k=3) + s(pinkStd, by=dummy, k=3) + dummy + s(yrFac, bs="re"), method="ML", data=fullDat)
pc2Pink <- gam(fl ~ s(pc2Std, by=dummy, k=3) + s(pinkStd, by=dummy, k=3) + dummy + s(yrFac, bs="re"), method="ML", data=fullDat)
alpiPink <- gam(fl ~ s(alpiStd, by=dummy, k=3) + s(pinkStd, by=dummy, k=3) + dummy + s(yrFac, bs="re"), method="ML", data=fullDat)
pdoSock <- gam(fl ~ s(pdoStd, by=dummy, k=3) + s(sockStd, by=dummy, k=3) + dummy + s(yrFac, bs="re"), method="ML", data=fullDat)
tempSock <- gam(fl ~ s(tempStd, by=dummy, k=3) + s(sockStd, by=dummy, k=3) + dummy + s(yrFac, bs="re"), method="ML", data=fullDat)
pc2Sock <- gam(fl ~ s(pc2Std, by=dummy, k=3) + s(sockStd, by=dummy, k=3) + dummy + s(yrFac, bs="re"), method="ML", data=fullDat)
alpiSock <- gam(fl ~ s(alpiStd, by=dummy, k=3) + s(sockStd, by=dummy, k=3) + dummy + s(yrFac, bs="re"), method="ML", data=fullDat)
pdoTotal <- gam(fl ~ s(pdoStd, by=dummy, k=3) + s(totalStd, by=dummy, k=3) + dummy + s(yrFac, bs="re"), method="ML", data=fullDat)
tempTotal <- gam(fl ~ s(tempStd, by=dummy, k=3) + s(totalStd, by=dummy, k=3) + dummy + s(yrFac, bs="re"), method="ML", data=fullDat)
pc2Total <- gam(fl ~ s(pc2Std, by=dummy, k=3) + s(totalStd, by=dummy, k=3) + dummy + s(yrFac, bs="re"), method="ML", data=fullDat)
alpiTotal <- gam(fl ~ s(alpiStd, by=dummy, k=3) + s(totalStd, by=dummy, k=3) + dummy + s(yrFac, bs="re"), method="ML", data=fullDat)


modRankings <- AICc(null, pdo, temp, pc2, alpi, pink, sock, total, pdoPink, tempPink, pc2Pink, alpiPink, 
	pdoSock, tempSock, pc2Sock, alpiSock, pdoTotal, tempTotal, pc2Total, alpiTotal)
modRankings[order(modRankings$AICc),]
summary(pdoSock)


### Generate predictions for age/watershed intercepts, competitor effects, and environmental drivers
datLength <- 100*length(unique(fullDat$dummy))
fullTempDat <- data.frame(yrFac = rep(unique(fullDat$yrFac), length.out = datLength),
						  sockStd = rep(0, length.out = datLength),
						  pdoStd = rep(seq(from = -2.5, to = 2.5, length = 100), times = 10),
						  dummy = rep(unique(fullDat$dummy), each = 100)
	)
predTempDat <- predict(pdoSock, fullTempDat, se.fit = TRUE, exclude = "s(yrFac)")
predTempDat <- with(predTempDat, data.frame(predTempDat,
											response = fit,
											lwr = (fit - 1.96*se.fit),
											upr = (fit + 1.96*se.fit))
	)
strsplit(as.character(fullTempDat$dummy)[1], " ")

plotPredictions <- function(dataset, splitBy, )


