# HISTORICAL SOCKEYE ANALYSIS - CLEMENS & GILBERT
# Created by C Freshwater JAN 21, 2018
# Last revised: ONGOING
# Uses cleaned data generated by NASS_Jan2018_CFedits.R
# to model relationship between regional environmental drivers
# and historical changes in sockeye body size
# -------------------------------------------------

setwd("/Users/cam/github")

library(mgcv); library(dplyr); library(ggplot2); library(reshape2); library(here)


sstPca <- read.table(here("github/histSockeye/data/sstPCA.txt")) #principal components of SST variation in NE Pacific (170E to 240E, 40N-65N)
sstRaw <- read.table(here("github/histSockeye/data/sstRaw.txt")) # pacific ocean SST
pdo <- read.csv(here("github/histSockeye/data/pdo.csv"), stringsAsFactors=F) 
meanAlpi <- read.csv(here("github/histSockeye/data/alpi.csv"), stringsAsFactors=F) #stops at 2015
sockDat <- read.csv(here("github/histSockeye/data/nassFullSox.csv"), stringsAsFactors=F)
catchDat <- read.csv(here("github/histSockeye/data/cleanAgCatch.csv"), stringsAsFactors=F)


## ---------------------- Clean ------------------------------
### sst PCA
colnames(sstPca) <- c("id", "retYr", "month", "pc1", "pc2", "pc3", "pc4", "pc5")
months <- c("3","4","5","6")
sstPca <- sstPca[sstPca$month %in% months, c("retYr","month","pc2")] 
meanPca <- sstPca %>%
	group_by(retYr) %>%
	summarise(pc2=mean(pc2))
meanPca$pc2Std <- (meanPca$pc2 - mean(meanPca$pc2))/sd(meanPca$pc2)

### sst raw
colnames(sstRaw) <- c("long", "lat", "retYr", "month", "temp")
months <- c("3","4","5","6")
sstRaw <- sstRaw[sstRaw$month %in% months, c("retYr","month","temp")] 
meanSst <- sstRaw %>%
	group_by(retYr) %>%
	summarise(temp=mean(temp))
meanSst$tempStd <- (meanSst$temp - mean(meanSst$temp))/sd(meanSst$temp)

### pdo
meanPdo <- data.frame(retYr=pdo$YEAR,
					  pdo=apply(pdo[,c("MAR","APR","MAY","JUN")], 1, mean)
					  )
meanPdo$pdoStd <- (meanPdo$pdo - mean(meanPdo$pdo))/sd(meanPdo$pdo)

### alpi
names(meanAlpi)[1:2] <- c("retYr", "alpi")
meanAlpi$alpiStd <- (meanAlpi$alpi - mean(meanAlpi$alpi))/sd(meanAlpi$alpi)

### catch
sockCatch <- catchDat[catchDat$species=="Sockeye", -c(1,2,4)]
names(sockCatch)[c(1,2)] <- c("retYr", "sockCatch")
sockCatch$sockStd <- (sockCatch$sockCatch - mean(sockCatch$sockCatch))/sd(sockCatch$sockCatch)
pinkCatch <- catchDat[catchDat$species=="Pink", -c(1,2,4)]
names(pinkCatch)[c(1,2)] <- c("retYr", "pinkCatch")
pinkCatch$pinkStd <- (pinkCatch$pinkCatch - mean(pinkCatch$pinkCatch))/sd(pinkCatch$pinkCatch)
totalCatch <- data.frame(retYr = sockCatch$retYr, totalCatch = (sockCatch$sockCatch + pinkCatch$pinkCatch))
totalCatch$totalStd <- (totalCatch$totalCatch - mean(totalCatch$totalCatch))/sd(totalCatch$totalCatch)

### merge sox data w/ environmental
fullDat <- Reduce(function(x, y) merge(x, y, by=c("retYr")), list(sockDat, meanPdo, meanSst, meanPca, meanAlpi, sockCatch, pinkCatch, totalCatch))

nassDat <- subset(fullDat, fullDat$watershed %in% "nass")
nassDatMod <- subset(nassDat, nassDat$dataSet %in% "mod")
nassDat <- subset(nassDat, nassDat$dataSet %in% "hist")
riversDat <- subset(fullDat,fullDat$watershed %in% "rivers")

nassDat$age <- factor(nassDat$age)
nassDat$retYr <- factor(nassDat$retYr)
nassDatMod$age <- factor(nassDatMod$age)
nassDatMod$retYr <- factor(nassDatMod$retYr)
riversDat$age <- factor(riversDat$age)
riversDat$retYr <- factor(riversDat$retYr)

datList <- list(nassDat, nassDatMod, riversDat)

# -----------------------------------------------
meanDat <- fullDat %>%
	group_by(retYr, age, watershed, dataSet) %>%
	summarize(meanFL = mean(fl), pdo = mean(pdo), alpi = mean(alpi), 
		rawSst = mean(temp), pcaSst = mean(pc2), pink = mean(pinkCatch), 
		sox = mean(sockCatch))

## Changes in length through time
ggplot(meanDat, aes(x = as.numeric(retYr), y = meanFL)) + 
    geom_line() + 
    facet_wrap(~ watershed)

# meanNassDat <- meanDat[meanDat$watershed=="nass",]
# meanNassDat <- meanNassDat[meanNassDat$dataSet=="hist",]

# -----------------------------------------------
## Initial model exploration to decide on structure
# ltNMod1 <- gamm(fl ~ s(pdo, by=age, k=3) + age, random=list(retYr = ~ 1), data=nassDat, method="REML")
# ltNMod1b <- gamm(fl ~ s(pdo, by=age, k=3) + age, random=list(retYr = ~ 1), correlation=corAR1(form = ~ 1|retYr), data=nassDat, method="REML")
# ltNMod1c <- gam(fl ~ s(pdo, by=age, k=3) + age + s(retYr, bs="re"), data=nassDat, method="REML")
# ltNMod1d <- gam(meanFL ~ s(pdo, by=age, k=3) + age, data=meanNassDat, method="REML")

# acf(residuals(ltNMod1c))
# summary(ltNMod1c)
# summary(ltNMod1$lme)

# ------------------------------------------------------
## Full model comparison with different environmental covariates; removed AR1 terms because they don't seem to be doing anything
fitGams <- function(dataset){
	dataset$dum <- 1
	
	# models
	null <- gam(fl ~ age + s(retYr, bs="re", by=dum), method="ML", data=dataset)
	pdo <- gam(fl ~ s(pdoStd, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=dataset)
	temp <- gam(fl ~ s(tempStd, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=dataset)
	pc2 <- gam(fl ~ s(pc2Std, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=dataset)
	alpi <- gam(fl ~ s(alpiStd, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=dataset)
	pink <- gam(fl ~ s(pinkStd, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=dataset)
	sock <- gam(fl ~ s(sockStd, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=dataset)
	total <- gam(fl ~ s(totalStd, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=dataset)
	pdoPink <- gam(fl ~ s(pdoStd, by=age, k=3) + s(pinkStd, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=dataset)
	tempPink <- gam(fl ~ s(tempStd, by=age, k=3) + s(pinkStd, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=dataset)
	pc2Pink <- gam(fl ~ s(pc2Std, by=age, k=3) + s(pinkStd, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=dataset)
	alpiPink <- gam(fl ~ s(alpiStd, by=age, k=3) + s(pinkStd, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=dataset)
	pdoSock <- gam(fl ~ s(pdoStd, by=age, k=3) + s(sockStd, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=dataset)
	tempSock <- gam(fl ~ s(tempStd, by=age, k=3) + s(sockStd, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=dataset)
	pc2Sock <- gam(fl ~ s(pc2Std, by=age, k=3) + s(sockStd, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=dataset)
	alpiSock <- gam(fl ~ s(alpiStd, by=age, k=3) + s(sockStd, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=dataset)
	pdoTotal <- gam(fl ~ s(pdoStd, by=age, k=3) + s(totalStd, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=dataset)
	tempTotal <- gam(fl ~ s(tempStd, by=age, k=3) + s(totalStd, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=dataset)
	pc2Total <- gam(fl ~ s(pc2Std, by=age, k=3) + s(totalStd, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=dataset)
	alpiTotal <- gam(fl ~ s(alpiStd, by=age, k=3) + s(totalStd, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=dataset)

	#aic 
	modRankings <- AICc(null, pdo, temp, pc2, alpi, pink, sock, total, pdoPink, tempPink, pc2Pink, alpiPink, 
		pdoSock, tempSock, pc2Sock, alpiSock, pdoTotal, tempTotal, pc2Total, alpiTotal)
	print(modRankings)
}

lapply(datList, function(x) fitGams(x))


ltNMod2 <- gam(fl ~ s(nSSTreturn1, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=nassDat)
ltNMod3 <- gam(fl ~ s(bSSTreturn1, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=nassDat)
ltNMod4 <- gam(fl ~ s(ALPIreturn1, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=nassDat)
ltNMod1b <- gam(fl ~ s(PDOreturn1, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=nassDat)
ltNMod2b <- gam(fl ~ s(nSSTreturn1, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=nassDat)
ltNMod3b <- gam(fl ~ s(bSSTreturn1, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=nassDat)
ltNMod4b <- gam(fl ~ s(ALPIreturn1, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=nassDat)
ltNMod1p <- gam(fl ~ s(PDOreturn1, by=age, k=3) + s(pinkSE1, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=nassDat)
ltNMod2p <- gam(fl ~ s(nSSTreturn1, by=age, k=3) + s(pinkSE1, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=nassDat)
ltNMod3p <- gam(fl ~ s(bSSTreturn1, by=age, k=3) + s(pinkSE1, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=nassDat)
ltNMod4p <- gam(fl ~ s(ALPIreturn1, by=age, k=3) + s(pinkSE1, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=nassDat)

AICc(ltNMod1,ltNMod2,ltNMod3,ltNMod4,ltNMod1b,ltNMod2b,ltNMod3b,ltNMod4b,
	ltNMod1p,ltNMod2p,ltNMod3p,ltNMod4p)
# top model is ltNMod2p nearshore and pink

gam.check(ltNMod2p)
acf(residuals(ltNMod2p), main = "") #no autocorrelation present in residuals
plot(ltNMod2p$gam, all.terms=TRUE, rug=FALSE)
plot_smooth(ltNMod2p, view="nSSTreturn1", plot_all="age", rm.ranef=TRUE,)
summary(ltNMod2p$gam)
summary(ltNMod2p$lme)


# Rivers
riversDat$dum <- 1
ltRMod1 <- gam(fl ~ s(PDOreturn1, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=riversDat)
ltRMod2 <- gam(fl ~ s(nSSTreturn1, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=riversDat)
ltRMod3 <- gam(fl ~ s(bSSTreturn1, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=riversDat)
ltRMod4 <- gam(fl ~ s(ALPIreturn1, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=riversDat)
ltRMod1b <- gam(fl ~ s(PDOreturn1, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=riversDat)
ltRMod2b <- gam(fl ~ s(nSSTreturn1, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=riversDat)
ltRMod3b <- gam(fl ~ s(bSSTreturn1, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=riversDat)
ltRMod4b <- gam(fl ~ s(ALPIreturn1, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=riversDat)
ltRMod1p <- gam(fl ~ s(PDOreturn1, by=age, k=3) + s(pinkSE1, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=riversDat)
ltRMod2p <- gam(fl ~ s(nSSTreturn1, by=age, k=3) + s(pinkSE1, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=riversDat)
ltRMod3p <- gam(fl ~ s(bSSTreturn1, by=age, k=3) + s(pinkSE1, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=riversDat)
ltRMod4p <- gam(fl ~ s(ALPIreturn1, by=age, k=3) + s(pinkSE1, by=age, k=3) + age + s(retYr, bs="re", by=dum), method="ML", data=riversDat)

AICc(ltRMod1,ltRMod2,ltRMod3,ltRMod4,ltRMod1b,ltRMod2b,ltRMod3b,ltRMod4b,
	ltRMod1p,ltRMod2p,ltRMod3p,ltRMod4p)
# top model is ltRMod1p (PDO and pink)

gam.check(ltRMod1p$gam)
acf(residuals(ltRMod1p$gam), main = "")
plot(ltRMod1p$gam, all.terms=TRUE, rug=FALSE)
plot_smooth(ltRMod1p$gam, view="PDOreturn1", plot_all="age", rm.ranef=TRUE,)
summary(ltRMod1p$gam)
summary(ltRMod1p$lme)



# -------------------------Clean figures of predictions-----------------------------

## Nass
ltNMod2p <- gam(fl ~ s(nSSTreturn1, by=age, k=3) + s(pinkSE1, by=age, k=3) + age + s(retYr, bs="re", by=dum), 
	correlation=corAR1(form = ~ 1|retYr), data=nassDat, method="REML")
## Mean response across SST, i.e. pink at mean
newNTempDat <- data.frame(retYr=rep(unique(nassDat$retYr), length.out=400), 
					pinkSE1=rep(0, length=400),
					nSSTreturn1=rep(seq(from=-2, to=2.5, length=100), times=4),
					age=rep(c("1.2", "1.3", "2.2", "2.3"), each=100),
					dum=0)
predNTempDat <- predict(ltNMod2p, newNTempDat, se.fit = TRUE)
predNTempDat <- with(predNTempDat, data.frame(newNTempDat,
								response = fit,
								lwr = (fit - 2*se.fit),
								upr = (fit + 2*se.fit)))

## Mean response across pinks, i.e. SST at mean
newNPinkDat <- data.frame(retYr=rep(unique(nassDat$retYr), length.out=400), 
					nSSTreturn1=rep(0, length=400),
					pinkSE1=rep(seq(from=-2, to=2.5, length=100), times=4),
					age=rep(c("1.2", "1.3", "2.2", "2.3"), each=100),
					dum=0)
predNPinkDat <- predict(ltNMod2p, newNPinkDat, se.fit = TRUE)
predNPinkDat <- with(predNPinkDat, data.frame(newNPinkDat,
								response = fit,
								lwr = (fit - 2*se.fit),
								upr = (fit + 2*se.fit)))

nassTempFig <- ggplot(predNTempDat, aes(x = nSSTreturn1, y = response, colour = age)) +
geom_ribbon(aes(ymin = lwr, ymax = upr, fill = age), alpha = 0.1) +
geom_line(aes(colour = age)) +
ylab("Fork Length") +
xlab("Standardized Nearshore SST") +
ggtitle("Nass SST Predictions")

nassPinkFig <- ggplot(predNPinkDat, aes(x = pinkSE1, y = response, colour = age)) +
geom_ribbon(aes(ymin = lwr, ymax = upr, fill = age), alpha = 0.1) +
geom_line(aes(colour = age)) +
ylab("Fork Length") +
xlab("Standardized Pink Abundance") +
ggtitle("Nass Pink Salmon Predictions")


## Rivers
riversDat$dum <- 1	
ltRMod1pY <- gam(fl ~ s(PDOreturn1, by=age, k=3) + s(pinkSE1, by=age, k=3) + age + s(retYr, bs="re", by=dum), 
	correlation=corAR1(form = ~ 1|retYr), data=riversDat, method="REML")

## Mean response across SST, i.e. pink at mean
newRPdoDat <- data.frame(retYr=rep(unique(riversDat$retYr), length.out=400), 
					pinkSE1=rep(0, length=400),
					PDOreturn1=rep(seq(from=-2, to=2.5, length=100), times=4),
					age=rep(c("1.2", "1.3"), each=200),
					dum=0)
predRPdoDat <- predict(ltRMod1pY, newRPdoDat, se.fit = TRUE)
predRPdoDat <- with(predRPdoDat, data.frame(newRPdoDat,
								response = fit,
								lwr = (fit - 2*se.fit),
								upr = (fit + 2*se.fit)))

## Mean response across pinks, i.e. SST at mean
newRPinkDat <- data.frame(retYr=rep(unique(riversDat$retYr), length.out=400), 
					PDOreturn1=rep(0, length=400),
					pinkSE1=rep(seq(from=-2, to=2.5, length=100), times=4),
					age=rep(c("1.2", "1.3"), each=200),
					dum=0)
predRPinkDat <- predict(ltRMod1pY, newRPinkDat, se.fit = TRUE)
predRPinkDat <- with(predRPinkDat, data.frame(newRPinkDat,
								response = fit,
								lwr = (fit - 2*se.fit),
								upr = (fit + 2*se.fit)))

rivPdoFig <- ggplot(predRPdoDat, aes(x = PDOreturn1, y = response, colour = age)) +
geom_ribbon(aes(ymin = lwr, ymax = upr, fill = age), alpha = 0.1) +
geom_line(aes(colour = age)) +
ylab("Fork Length") +
xlab("Stnadardized PDO") +
ggtitle("Rivers PDO Predictions")

rivPinkFig <- ggplot(predRPinkDat, aes(x = pinkSE1, y = response, colour = age)) +
geom_ribbon(aes(ymin = lwr, ymax = upr, fill = age), alpha = 0.1) +
geom_line(aes(colour = age)) +
ylab("Fork Length") +
xlab("Standardized Pink Abundance") +
ggtitle("Rivers Pink Salmon Predictions")


# Save figures
pdf(here("NassRivers/figs/predictions.pdf"), height=4, width=4)
theme_set(theme_bw())
nassTempFig
nassPinkFig
rivPdoFig
rivPinkFig
dev.off()


# -------------------------Truncated models-----------------------------
# Truncated models to pass to Skip to compare w/ SST
nassDat$dum <- 1	
ltNTrunc1 <- gam(fl ~ s(pinkSE1, by=age, k=3) + age + s(retYr, bs="re", by=dum), 
	correlation=corAR1(form = ~ 1|retYr), data=nassDat, method="REML")
ltNTrunc2 <- gam(fl ~ age + s(retYr, bs="re", by=dum), 
	correlation=corAR1(form = ~ 1|retYr), data=nassDat, method="REML")
nassDat$residPink <- resid(ltNTrunc1)
nassDat$residNoPink <- resid(ltNTrunc2)
write.csv(nassDat, here("github/histSockeye/outputs/data/nassDatWResids.csv"))

riversDat$dum <- 1	
ltRTrunc1 <- gam(fl ~ s(pinkSE1, by=age, k=3) + age + s(retYr, bs="re", by=dum), 
	correlation=corAR1(form = ~ 1|retYr), data=riversDat, method="REML")
ltRTrunc2 <- gam(fl ~ age + s(retYr, bs="re", by=dum), 
	correlation=corAR1(form = ~ 1|retYr), data=riversDat, method="REML")
riversDat$residPink <- resid(ltRTrunc1)
riversDat$residNoPink <- resid(ltRTrunc2)
write.csv(riversDat, here("github/histSockeye/outputs/data/riversDatWResids.csv"))







