# HISTORICAL SOCKEYE ANALYSIS - CLEMENS & GILBERT
# Created by CF JAN 21, 2018
# Uses cleaned data generated by NASS_Jan2018_CFedits.R
# to model relationship between regional environmental drivers
# and historical changes in sockeye body size
# -------------------------------------------------


setwd("/Users/cam/cam\ stuff/Grad\ School/JuvSockeyeData/Analysis/NassRivers")


library(mgcv); library(nlme); library(usdm); library(MuMIn); library(itsadug); library(dplyr); library(ggplot2); library(reshape2); library(here)


fullHistDat <- read.csv("data/histSockDat.csv", stringsAsFactors=F)
fullHistDat$pinkSE1<-(fullHistDat$pink_SE - mean(fullHistDat$pink_SE))/(sd(fullHistDat$pink_SE))


histDat <- fullHistDat[,c("watershed","retYr","entry.yr","WEIGHT_g","LENGTH_mm","AGE","K","PDOreturn1",
	"ALPIreturn1","nSSTreturn1","bSSTreturn1","pinkSE1")]

names(histDat)[c(3:6)] <- c("entryYr", "wt", "fl", "age")


histDat$marAge <- ifelse(histDat$age=="1.3" | histDat$age=="2.3", 1, 0)
histDat$marage <- as.factor(histDat$marage)
histDat$watershed <- as.factor(histDat$watershed)
histDat$age <- as.factor(histDat$age)
histDat$retYr <- as.factor(histDat$retYr)

nassDat <- subset(histDat,histDat$watershed %in% "nass")
riversDat <- subset(histDat,histDat$watershed %in% "rivers")

nassDat$age <- factor(nassDat$age)
nassDat$retYr <- factor(nassDat$retYr)
riversDat$age <- factor(riversDat$age)
riversDat$retYr <- factor(riversDat$retYr)

# -----------------------------------------------
meanHist <- histDat %>%
	group_by(retYr, watershed) %>%
	summarize(meanFL = mean(fl), meanWt = mean(wt), meanK = mean(K), retPDO = mean(PDOreturn1),
		retPink = mean(ALPIreturn1), retSSTn = mean(nSSTreturn1), retSSTb = mean(bSSTreturn1))

## Changes in length through time
ggplot(meanHist[meanHist$watershed=="nass",], aes(x = as.numeric(retYr), y = meanFL)) + 
    geom_line() + 
    facet_wrap(~ age)
ggplot(meanHist[meanHist$watershed=="rivers",], aes(x = as.numeric(retYr), y = meanFL)) + 
    geom_line() + 
    facet_wrap(~ age)


meanNass <- meanHist[meanHist$watershed=="nass",c(1,3)]    
meanRivers <- meanHist[meanHist$watershed=="rivers",c(1,3)]    

plot(meanNass$meanFL ~ meanRivers$meanFL[-c(1,27,28,29)])


# Plot changes in age structure through time
temp <- nassDat[,c("retYr", "age")]
temp2 <- prop.table(table(temp), 1)
nassage <- as.data.frame(melt(temp2))
names(nassage) <- c("retYr", "age", "ppn")

temp <- riversDat[,c("retYr", "age")]
temp2 <- prop.table(table(temp), 1)
riversage <- as.data.frame(melt(temp2))
names(riversage) <- c("retYr", "age", "ppn")

pdf(here("NassRivers/figs/ageStruc.pdf"), height=4, width=4)
ggplot(nassage, aes(x = retYr, y = ppn, fill = as.factor(age)))  +
	geom_area(position = 'stack') +
	xlab("Return Year") +
	ylab("Proportion") +
	scale_fill_discrete(name = "age")
ggplot(riversage, aes(x = retYr, y = ppn, fill = as.factor(age))) +
	geom_area(position = 'stack') +
	xlab("Return Year") +
	ylab("Proportion") +
	scale_fill_discrete(name = "age")
dev.off()

# -----------------------------------------------
## Initial model exploration to decide on structure

# ltMod1 <- gamm(fl ~ s(PDOreturn1, by=watershed, k=3), random=list(retYr = ~ 1), correlation=corAR1(form = ~ 1|retYr), data=histDat)
# ltMod1b <- gamm(fl ~ s(PDOreturn1, by=watershed, k=3), random=list(retYr = ~ 1), data=histDat)
# ltMod1c <- gam(fl ~ s(PDOreturn1, by=watershed, k=3) + s(retYr, bs="re"), data=histDat, method="REML")
# # ltMod1d <- gam(meanFL ~ s(retPDO, by=watershed, k=3), data=meanHist, method="REML")
# ltMod1e <- gamm(fl ~ s(PDOreturn1, by=watershed, k=3) + watershed*age, random=list(retYr = ~ 1), correlation=corAR1(form = ~ 1|retYr), data=histDat)

# AICc(ltMod1,ltMod1b,ltMod1c,ltMod1e)
# # 1e superior; assume consistent across response variables

# pacf(resid(ltMod1$lme, type = "normalized"))
# pacf(resid(ltMod1e$gam, type = "deviance"))

# gam.check(ltMod1e$gam) #check for normal residuals and equal variances

# summary(ltMod1e) ## difficult estimating smoother significance and plotting with both watersheds in the same model
# #######################################################
# #######################################################

## Separate and test for where age should be included

ltNMod1 <- gamm(fl ~ s(PDOreturn1, k=3) + age, random=list(retYr = ~ 1), correlation=corAR1(form = ~ 1|retYr), data=nassDat)
ltNMod1b <- gamm(fl ~ s(PDOreturn1, by=age, k=3) + age, random=list(retYr = ~ 1), correlation=corAR1(form = ~ 1|retYr), data=nassDat)
ltNMod1c <- gamm(fl ~ s(PDOreturn1, by=age, k=3), random=list(retYr = ~ 1), correlation=corAR1(form = ~ 1|retYr), data=nassDat)
ltRMod1 <- gamm(fl ~ s(PDOreturn1, k=3) + age, random=list(retYr = ~ 1), correlation=corAR1(form = ~ 1|retYr), data=riversDat)
ltRMod1b <- gamm(fl ~ s(PDOreturn1, by=age, k=3) + age, random=list(retYr = ~ 1), correlation=corAR1(form = ~ 1|retYr), data=riversDat)
ltRMod1c <- gamm(fl ~ s(PDOreturn1, by=age, k=3), random=list(retYr = ~ 1), correlation=corAR1(form = ~ 1|retYr), data=riversDat)

AICc(ltNMod1,ltNMod1b,ltNMod1c)
AICc(ltRMod1,ltRMod1b,ltRMod1c)
# support for including age specific splines and fixed effects (i.e. b)



# ------------------------------------------------------
## Full model comparison with different environmental covariates
ctrl <- lmeControl(maxIter=500) #up max number of iterations to help difficult models converge
# Nass
ltNMod1 <- gam(fl ~ s(PDOreturn1, by=age, k=3) + age + s(retYr, bs="re", by=dum), correlation=corAR1(form = ~ 1|retYr), method="ML", data=nassDat)
ltNMod2 <- gam(fl ~ s(nSSTreturn1, by=age, k=3) + age + s(retYr, bs="re", by=dum), correlation=corAR1(form = ~ 1|retYr), method="ML", data=nassDat)
ltNMod3 <- gam(fl ~ s(bSSTreturn1, by=age, k=3) + age + s(retYr, bs="re", by=dum), correlation=corAR1(form = ~ 1|retYr), method="ML", data=nassDat)
ltNMod4 <- gam(fl ~ s(ALPIreturn1, by=age, k=3) + age + s(retYr, bs="re", by=dum), correlation=corAR1(form = ~ 1|retYr), method="ML", data=nassDat)
ltNMod1b <- gam(fl ~ s(PDOreturn1, k=3) + age + s(retYr, bs="re", by=dum), correlation=corAR1(form = ~ 1|retYr), method="ML", data=nassDat)
ltNMod2b <- gam(fl ~ s(nSSTreturn1, k=3) + age + s(retYr, bs="re", by=dum), correlation=corAR1(form = ~ 1|retYr), method="ML", data=nassDat)
ltNMod3b <- gam(fl ~ s(bSSTreturn1, k=3) + age + s(retYr, bs="re", by=dum), correlation=corAR1(form = ~ 1|retYr), method="ML", data=nassDat)
ltNMod4b <- gam(fl ~ s(ALPIreturn1, k=3) + age + s(retYr, bs="re", by=dum), correlation=corAR1(form = ~ 1|retYr), method="ML", data=nassDat)
ltNMod1p <- gam(fl ~ s(PDOreturn1, by=age, k=3) + s(pinkSE1, by=age, k=3) + age + s(retYr, bs="re", by=dum), correlation=corAR1(form = ~ 1|retYr), method="ML", data=nassDat)
ltNMod2p <- gam(fl ~ s(nSSTreturn1, by=age, k=3) + s(pinkSE1, by=age, k=3) + age + s(retYr, bs="re", by=dum), correlation=corAR1(form = ~ 1|retYr), method="ML", data=nassDat)
ltNMod3p <- gam(fl ~ s(bSSTreturn1, by=age, k=3) + s(pinkSE1, by=age, k=3) + age + s(retYr, bs="re", by=dum), correlation=corAR1(form = ~ 1|retYr), method="ML", data=nassDat)
ltNMod4p <- gam(fl ~ s(ALPIreturn1, by=age, k=3) + s(pinkSE1, by=age, k=3) + age + s(retYr, bs="re", by=dum), correlation=corAR1(form = ~ 1|retYr), method="ML", data=nassDat)

AICc(ltNMod1,ltNMod2,ltNMod3,ltNMod4,ltNMod1b,ltNMod2b,ltNMod3b,ltNMod4b,
	ltNMod1p,ltNMod2p,ltNMod3p,ltNMod4p)
# top model is ltNMod2p nearshore and pink

gam.check(ltNMod2p)
acf(residuals(ltNMod2p), main = "") #no autocorrelation present in residuals
plot(ltNMod2p$gam, all.terms=TRUE, rug=FALSE)
plot_smooth(ltNMod2p, view="nSSTreturn1", plot_all="age", rm.ranef=TRUE,)
summary(ltNMod2p$gam)
summary(ltNMod2p$lme)


# Rivers
ltRMod1 <- gam(fl ~ s(PDOreturn1, by=age, k=3) + age + s(retYr, bs="re", by=dum), correlation=corAR1(form = ~ 1|retYr), method="ML", data=riversDat)
ltRMod2 <- gam(fl ~ s(nSSTreturn1, by=age, k=3) + age + s(retYr, bs="re", by=dum), correlation=corAR1(form = ~ 1|retYr), method="ML", data=riversDat)
ltRMod3 <- gam(fl ~ s(bSSTreturn1, by=age, k=3) + age + s(retYr, bs="re", by=dum), correlation=corAR1(form = ~ 1|retYr), method="ML", data=riversDat)
ltRMod4 <- gam(fl ~ s(ALPIreturn1, by=age, k=3) + age + s(retYr, bs="re", by=dum), correlation=corAR1(form = ~ 1|retYr), method="ML", data=riversDat)
ltRMod1b <- gam(fl ~ s(PDOreturn1, k=3) + age + s(retYr, bs="re", by=dum), correlation=corAR1(form = ~ 1|retYr), method="ML", data=riversDat)
ltRMod2b <- gam(fl ~ s(nSSTreturn1, k=3) + age + s(retYr, bs="re", by=dum), correlation=corAR1(form = ~ 1|retYr), method="ML", data=riversDat)
ltRMod3b <- gam(fl ~ s(bSSTreturn1, k=3) + age + s(retYr, bs="re", by=dum), correlation=corAR1(form = ~ 1|retYr), method="ML", data=riversDat)
ltRMod4b <- gam(fl ~ s(ALPIreturn1, k=3) + age + s(retYr, bs="re", by=dum), correlation=corAR1(form = ~ 1|retYr), method="ML", data=riversDat)
ltRMod1p <- gam(fl ~ s(PDOreturn1, by=age, k=3) + s(pinkSE1, by=age, k=3) + age + s(retYr, bs="re", by=dum), correlation=corAR1(form = ~ 1|retYr), method="ML", data=riversDat)
ltRMod2p <- gam(fl ~ s(nSSTreturn1, by=age, k=3) + s(pinkSE1, by=age, k=3) + age + s(retYr, bs="re", by=dum), correlation=corAR1(form = ~ 1|retYr), method="ML", data=riversDat)
ltRMod3p <- gam(fl ~ s(bSSTreturn1, by=age, k=3) + s(pinkSE1, by=age, k=3) + age + s(retYr, bs="re", by=dum), correlation=corAR1(form = ~ 1|retYr), method="ML", data=riversDat)
ltRMod4p <- gam(fl ~ s(ALPIreturn1, by=age, k=3) + s(pinkSE1, by=age, k=3) + age + s(retYr, bs="re", by=dum), correlation=corAR1(form = ~ 1|retYr), method="ML", data=riversDat)

AICc(ltRMod1,ltRMod2,ltRMod3,ltRMod4,ltRMod1b,ltRMod2b,ltRMod3b,ltRMod4b,
	ltRMod1p,ltRMod2p,ltRMod3p,ltRMod4p)
# top model is ltRMod1p (PDO and pink)

gam.check(ltRMod1p$gam)
acf(residuals(ltRMod1p$gam), main = "")
plot(ltRMod1p$gam, all.terms=TRUE, rug=FALSE)
plot_smooth(ltRMod1p$gam, view="PDOreturn1", plot_all="age", rm.ranef=TRUE,)
summary(ltRMod1p$gam)
summary(ltRMod1p$lme)



# -------------------------Clean figures of predictions-----------------------------

## Nass
nassDat$dum <- 1	
ltNMod2pY <- gam(fl ~ s(nSSTreturn1, by=age, k=3) + s(pinkSE1, by=age, k=3) + age + s(retYr, bs="re", by=dum), 
	correlation=corAR1(form = ~ 1|retYr), data=nassDat, method="REML")

# ltRMod1p <- gamm(fl ~ s(PDOreturn1, by=age, k=3) + s(pinkSE1, by=age, k=3) + age, random=list(retYr = ~ 1), correlation=corAR1(form = ~ 1|retYr), data=riversDat)

## Mean response across SST, i.e. pink at mean
newNTempDat <- data.frame(retYr=rep(unique(nassDat$retYr), length.out=400), 
					pinkSE1=rep(0, length=400),
					nSSTreturn1=rep(seq(from=-2, to=2.5, length=100), times=4),
					age=rep(c("1.2", "1.3", "2.2", "2.3"), each=100),
					dum=0)
predNTempDat <- predict(ltNMod2pY, newNTempDat, se.fit = TRUE)
predNTempDat <- with(predNTempDat, data.frame(newNTempDat,
								response = fit,
								lwr = (fit - 2*se.fit),
								upr = (fit + 2*se.fit)))

## Mean response across pinks, i.e. SST at mean
newNPinkDat <- data.frame(retYr=rep(unique(nassDat$retYr), length.out=400), 
					nSSTreturn1=rep(0, length=400),
					pinkSE1=rep(seq(from=-2, to=2.5, length=100), times=4),
					age=rep(c("1.2", "1.3", "2.2", "2.3"), each=100),
					dum=0)
predNPinkDat <- predict(ltNMod2pY, newNPinkDat, se.fit = TRUE)
predNPinkDat <- with(predNPinkDat, data.frame(newNPinkDat,
								response = fit,
								lwr = (fit - 2*se.fit),
								upr = (fit + 2*se.fit)))

nassTempFig <- ggplot(predNTempDat, aes(x = nSSTreturn1, y = response, colour = age)) +
geom_ribbon(aes(ymin = lwr, ymax = upr, fill = age), alpha = 0.1) +
geom_line(aes(colour = age)) +
ylab("Fork Length") +
xlab("Standardized Nearshore SST") +
ggtitle("Nass SST Predictions")

nassPinkFig <- ggplot(predNPinkDat, aes(x = pinkSE1, y = response, colour = age)) +
geom_ribbon(aes(ymin = lwr, ymax = upr, fill = age), alpha = 0.1) +
geom_line(aes(colour = age)) +
ylab("Fork Length") +
xlab("Standardized Pink Abundance") +
ggtitle("Nass Pink Salmon Predictions")


## Rivers
riversDat$dum <- 1	
ltRMod1pY <- gam(fl ~ s(PDOreturn1, by=age, k=3) + s(pinkSE1, by=age, k=3) + age + s(retYr, bs="re", by=dum), 
	correlation=corAR1(form = ~ 1|retYr), data=riversDat, method="REML")

## Mean response across SST, i.e. pink at mean
newRPdoDat <- data.frame(retYr=rep(unique(riversDat$retYr), length.out=400), 
					pinkSE1=rep(0, length=400),
					PDOreturn1=rep(seq(from=-2, to=2.5, length=100), times=4),
					age=rep(c("1.2", "1.3"), each=200),
					dum=0)
predRPdoDat <- predict(ltRMod1pY, newRPdoDat, se.fit = TRUE)
predRPdoDat <- with(predRPdoDat, data.frame(newRPdoDat,
								response = fit,
								lwr = (fit - 2*se.fit),
								upr = (fit + 2*se.fit)))

## Mean response across pinks, i.e. SST at mean
newRPinkDat <- data.frame(retYr=rep(unique(riversDat$retYr), length.out=400), 
					PDOreturn1=rep(0, length=400),
					pinkSE1=rep(seq(from=-2, to=2.5, length=100), times=4),
					age=rep(c("1.2", "1.3"), each=200),
					dum=0)
predRPinkDat <- predict(ltRMod1pY, newRPinkDat, se.fit = TRUE)
predRPinkDat <- with(predRPinkDat, data.frame(newRPinkDat,
								response = fit,
								lwr = (fit - 2*se.fit),
								upr = (fit + 2*se.fit)))

rivPdoFig <- ggplot(predRPdoDat, aes(x = PDOreturn1, y = response, colour = age)) +
geom_ribbon(aes(ymin = lwr, ymax = upr, fill = age), alpha = 0.1) +
geom_line(aes(colour = age)) +
ylab("Fork Length") +
xlab("Stnadardized PDO") +
ggtitle("Rivers PDO Predictions")

rivPinkFig <- ggplot(predRPinkDat, aes(x = pinkSE1, y = response, colour = age)) +
geom_ribbon(aes(ymin = lwr, ymax = upr, fill = age), alpha = 0.1) +
geom_line(aes(colour = age)) +
ylab("Fork Length") +
xlab("Standardized Pink Abundance") +
ggtitle("Rivers Pink Salmon Predictions")


# Save figures
pdf(here("NassRivers/figs/predictions.pdf"), height=4, width=4)
theme_set(theme_bw())
nassTempFig
nassPinkFig
rivPdoFig
rivPinkFig
dev.off()




