# HISTORICAL SOCKEYE ANALYSIS - GILBERT & CLEMENS, BILTON, & MODERN NISGA'A DATA
# Created by J Weil DEC 6, 2019
# Adapted from previous script by C Freshwater JAN 21, 2018
# Last revised: ONGOING
# Uses cleaned data generated by NASS_Jan2018_CFedits.R
# to model variability in Sockeye size-at-age from 1914 to 2019
# -------------------------------------------------

library(tidyverse); library(dplyr); library(ggplot2)


## Remove the here::here if you're using setwd
gc <- read.csv(here::here("data", "nass_data_GC_trimmed.csv"), stringsAsFactors=F)
#bilt <- read.csv(("nass_data_BILTON.csv"), stringsAsFactors=F)
#monk <- read.csv(("nass_data_MONKLEY.csv"), stringsAsFactors=F)
mod <- read.csv(here::here("data", "nass_data_MOD_trimmed.csv"), stringsAsFactors=F)


## ---------------------- Prepping datasets for models ------------------------


## Make a single, trimmed dataset to compare only the variables we are plotting (FL, DOY, SEX, AGE, YEAR)
gc_trim <- data.frame(gc$FL_mm,gc$DAYOFYR,gc$SEX,gc$AGE,gc$YEAR)
colnames(gc_trim) <- c("FL","DOY","SEX","AGE","YEAR")
#bilt_trim <- data.frame(bilt$FL_mm,bilt$DAYOFYR,bilt$SEX,bilt$AGE,bilt$YEAR)
#colnames(bilt_trim) <- c("FL","DOY","SEX","AGE","YEAR")
#monk_trim <- data.frame(monk$FL_mm,monk$DAYOFYR,monk$SEX,monk$AGE,monk$YEAR)
#colnames(monk_trim) <- c("FL","DOY","SEX","AGE","YEAR")
mod_trim <- data.frame(mod$FL_mm,mod$DAYOFYR,mod$SEX,mod$AGE,mod$YEAR)
colnames(mod_trim) <- c("FL","DOY","SEX","AGE","YEAR")


## Bind datasets ##
#FullDataset <- rbind(gc_trim,bilt_trim,monk_trim,mod_trim)
FullDataset <- rbind(gc_trim,mod_trim) %>% 
  mutate(zDOY = as.numeric(scale(DOY)), # scale DOY
         AGE = as.factor(AGE),
         YEAR = as.factor(YEAR))
# We scale DOY because we want to account for it in the model, but we don't
# really care about making predictions associated witha  specific day of year.
# If it's scaled we can remove its effect (i.e. set it at a mean value) by 
# setting it to 0 (see pred_dat below)


## Calculate average DOY of returning fish per year ##
# CF NOTE: Using average DOY isn't necessary, we can just use individual values
# within the model
# DOY_agg <- FullDataset %>%
#   group_by(YEAR) %>%
#   summarise_at(vars(DOY), list(mean = mean), as.factor=TRUE)
# colnames(DOY_agg) <- c("YEAR","DOY_agg")

## Bind DOY_agg with full dataset ##
# full <- merge(FullDataset,DOY_agg, by="YEAR")


## ---------------------- Plotting size trends ------------------------------

### Code below may be more appropriate
## Changes in length through time
# index <- unique(model$dummy)
# pdf(("/Users/JacobWeil/Desktop/Sockeye_2019/figs/linearTrends.pdf"), height=6, width=6)
# for(i in seq_along(index)) {
#   d <- model[model$dummy == index[i], ]
#   p <- ggplot(d, aes(x = as.numeric(YEAR), y = FL, col = as.factor(AGE))) + 
#     geom_point() + 
#     geom_smooth(method = "lm") +
#     ggtitle(index[i])
#   print(p)
# }
# dev.off()


library(lme4)
library(merTools)

# This is the first model I tried. It's incorrect because it assumes that the 
# age effect is stable through time (i.e. temporal trends are the same 
# regardless of age at maturity), but look at the predictions to see for yourself
mod <- lmer(FL ~ zDOY + SEX + AGE + (1 | YEAR), data = FullDataset,
            REML = FALSE)
# This is the model I think we should use. Basically FL is a function of run timing
# sex, and age-at-maturity. Samples within a given age and year are more similar 
# to one another than not (i.e. covary). This is accounted for in the random effects 
mod1 <- lmer(FL ~ zDOY + SEX + AGE + (1 | AGE:YEAR), data = FullDataset,
             REML = FALSE)
summary(mod1)
mod1b <- lmer(FL ~ zDOY + AGE + (1 | AGE:YEAR), data = FullDataset,
             REML = FALSE)
AIC(mod1, mod1b)

mod_f <- lm(FL ~ as.numeric(zDOY) + SEX + AGE:YEAR, data = FullDataset)
summary(mod_f)


# Generate a dataframe of predictive values, i.e. each age class, average entry 
# day (0 when scaled), a reference sex, and each year we have data for. 
# expand.grid is used to generate unique combinations of each variable
pred_dat <- expand.grid(AGE = c("42", "52", "53", "63"),
                        zDOY = 0,
                        SEX = "M",
                        YEAR = unique(FullDataset$YEAR)) 
# Geenrate confidences intervals for predictions based on model
preds0 <- predictInterval(mod, newdata = pred_dat, n.sims = 999)
preds <- predictInterval(mod1, newdata = pred_dat, n.sims = 999)
preds_fix <- predict.lm(mod_f, newdata = pred_dat, se.fit = TRUE)

# Bind confidence intervals to the predictive data for plotting
dat_out <- cbind(pred_dat, preds) %>% 
  # Add a factor representing sample collection to visualize effects 
  # NOTE: period is not modeled, we're simply assigning a color in the plot to 
  # each data set
  mutate(indYear = as.numeric(as.character(YEAR)),
         period = case_when(
           indYear < 1947 ~ "GC",
           indYear > 1993 ~ "mod"
         ))
ggplot(aes(x = YEAR, y=fit, ymin=lwr, ymax=upr, fill = as.factor(period)), 
       data = dat_out) +
  geom_point(shape = 21) + 
  geom_linerange() +
  labs(x="Index", y="Prediction w/ 95% PI") + 
  theme_bw() +
  facet_wrap(~AGE)

dat_out_f <- cbind(pred_dat, preds_fix) %>% 
  mutate(indYear = as.numeric(as.character(YEAR)),
         period = case_when(
           indYear < 1947 ~ "GC",
           indYear > 1993 ~ "mod"
         ),
         lwr = fit + (qnorm(0.025) * se.fit),
         upr = fit + (qnorm(0.975) * se.fit))
ggplot(aes(x = YEAR, y=fit, ymin=lwr, ymax=upr, fill = as.factor(period)), 
       data = dat_out_f) +
  geom_point(shape = 21) + 
  geom_linerange() +
  labs(x="Index", y="Prediction w/ 95% PI") + 
  theme_bw() +
  facet_wrap(~AGE)

dat_out_f %>% 
  filter(AGE == "42", 
         fit > 650)

tt <- FullDataset %>% 
  filter(AGE == "42", YEAR == "1935", SEX == "M") %>%
  # filter(AGE == "42") %>%
  # group_by(YEAR, SEX, AGE) %>% 
  summarize(n = length(unique(FL)))


# ------------------------------------------------------------------------------
## Fit each age class independently

a42 <- FullDataset %>% 
  filter(AGE == "42")
a52 <- FullDataset %>% 
  filter(AGE == "52")
a53 <- FullDataset %>% 
  filter(AGE == "53")
a63 <- FullDataset %>% 
  filter(AGE == "63")
dat_list <- list(a42, a52, a53, a63)

pred_dat <- expand.grid(zDOY = 0,
                        SEX = "F",
                        YEAR = unique(FullDataset$YEAR)) 

mod_fits_f <- map(dat_list, function(x) {
  fit <- lmer(FL ~ zDOY + SEX + (1 | YEAR), data = x,
       REML = TRUE)
  preds <- predictInterval(fit, newdata = pred_dat, n.sims = 999)
  # fit <- lm(FL ~ zDOY + SEX + YEAR, data = x)
  
  cbind(pred_dat, preds) %>% 
    mutate(age = unique(x$AGE),
           indYear = as.numeric(as.character(YEAR)),
           period = case_when(
             indYear < 1947 ~ "GC",
             indYear > 1993 ~ "mod"
           ))
}) %>% 
  bind_rows

ggplot(aes(x = YEAR, y=fit, ymin=lwr, ymax=upr, fill = as.factor(period)), 
       data = mod_fits) +
  geom_point(shape = 21) + 
  geom_linerange() +
  labs(x="Index", y="Prediction w/ 95% PI") + 
  theme_bw() +
  facet_wrap(~age)

ggplot(aes(x = YEAR, y=FL), data = FullDataset) +
  geom_boxplot() + 
  labs(x="Index", y="Observed") + 
  theme_bw() +
  facet_wrap(~AGE)
